version: '3.8'
## Conection to the frontend Nginx
networks:
  frontend:
    external: true
  backend:

volumes:
  wordpress-data:
  wordpress-db:

services:
  wordpress-app:
    image: wordpress:latest
    restart: always
    volumes:
      - ./wordpress-data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=wordpress-db
      - WORDPRESS_DB_USER=db_user
      - WORDPRESS_DB_PASSWORD=db_pass
      - WORDPRESS_DB_NAME=db_wordpress
    networks:
      - frontend
      - backend

  wordpress-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./wordpress-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=db_root_pass
      - MYSQL_DATABASE=db_wordpress
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_pass
    networks:
      - backend
